TuttoHomeController:
    resource: "@TuttoFrontendBundle/Controller/HomeController.php"
    type: annotation
    
TuttoDataGridBundle:
  resource: "@TuttoDataGridBundle/Resources/config/routes.yml"

TuttoSecurityBundle:
  resource: "@TuttoSecurityBundle/Resources/config/routes.yml"