services:
  security:
    class: Tutto\SecurityBundle\Service\PrivilegeCheckService
    calls:
      - [setContainer, ["@service_container"] ]
    tags:
      - { name: kernel.event_listener, event: kernel.controller, method: init }