RegistrationController:
  resource: '@TuttoSecurityBundle/Controller/RegistrationController.php'
  type: annotation

AuthController:
  resource: "@TuttoSecurityBundle/Controller/AuthController.php"
  type: annotation