security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    providers:
      fos_userbundle:
        id: fos_user.user_provider.username_email

    firewalls:
      main:
        pattern: ^/
        form_login:
          check_path: _login_check
          login_path: _login
          provider: fos_userbundle
          csrf_provider: form.csrf_provider
        logout:
          path: _logout
        anonymous: true

    access_control:
      - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
